name: Release github action

on:
  push:
    branches:
      - 'main'
  workflow_dispatch: # Allow manual triggers
  
permissions:
  contents: write

jobs:
  release-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run:  node setup.js
        
      - name: Install Dependencies
        run:  node main.js
        
